### ISSUE TITLE
Dial error

### ISSUE THREAD

**Issue by kikohnl** [fffilimonov/OCIP_go#1]
In the function func OCIPsend, if there is an error on the net Dialer, the code should bail out and not try to continue to run with possible invalid network connection information causing a SIGSEGV.

**Comment by fffilimonov** [comment]
Actually this project is not a good example of code.
And I don't use it anymore.
If you need it - you can send PR or just fork project.
If you have questions - welcome.

**Comment by kikohnl** [comment]
Vadim,

Is it really that bad of code, or do you just not use it anymore?

Iʻm just getting ready to migrate 10,000 lines in to Broadsoft, and this is the only OCI-P package for Go Lang that I found.

Thank you for the code!
Keith Otis

**Comment by fffilimonov** [comment]
I used this package in my other projects.
Now I'm not working with BW.
If you need to manage BW - try this one https://github.com/fffilimonov/BW_OCI-P/tree/master/OCI-P.
If you are going to build some system in Go I think it's better to rewrite OCI-P package
